# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the script file to the container
COPY PB_dispo_whole.py .

# Run the script when the container starts
CMD ["python", "PB_dispo_whole.py"]
